### PR TITLE
Allow conditional loading of IA bundles

### PR DESCRIPTION
**Pull request by zachthompson**
When developing it isn't necessary to have all IA types, e.g. goodie, spice, fathead, and longtail, loaded but only the type being worked on.  This change allows our bundles and their metadata to be conditionally loaded and used in DDG::Meta::Data.

Should help fix [issue #258](https://github.com/duckduckgo/p5-app-duckpan/issues/258), although at least one bundle is still required to be installed.

### CODE REVIEW

**Comment by russellholt** [comment]
LGTM

**Comment by russellholt** [comment]
I don't like the metadata loading functionality at the top level like this. I suggest making it accessible from a sub that takes a metadata file(s) as an argument and calling it externally at the right time, eg from core, or even from within Spice::DDG import, or in the _apply_keywords subs.

**Comment by zachthompson** [comment]
I don't follow.  The metadata has to be loaded immediately as apply_keywords is done at start up.  What would the "right time" be?

**Comment by russellholt** [comment]
Executing code with external dependencies at the top level, eg the main body, is just bad practice. It should be contained and called when ready.

**Pull request merged**
