### PR TITLE
Fix for https://github.com/duckduckgo/zeroclickinfo-goodies/issues/772.

### PR DESCRIPTION
**Pull request by mnp**
The fix consists of new class DDG::CountryCodes and basic unit tests.

This class factors out some spice and goodie usages of Locale::Country
where there was some organic copying. DDG-local aliases and renames
are centralized here.

Locale::Country is presented as a functional style library, but some of its
calls modify its state, so it's probably cleaner to use it wrapped as an
object for encapsulation.

*** NOTE *** - There are also followup PRs in spice and goodie which
    will depend on this patch.  Merge this one first please.

### CODE REVIEW

**Comment by mnp** [comment]
Rob, just returning to this issue after a context switch.

I'm not sure role is appropriate here because (1) this package has internal
state -- inside Locale, setting its process globals :-(  -- which should be
shared among all consumers, therefore (2) I need a way to initialize all
this state, and (3) I'd like it done once among multiple callers.

I didn't want to bring MooseX::Singleton into your stack, but that would
have been nicer solution for (3) than a secret ghetto global.  Because of
(1, 2), I want an initialization hook, and roles don't call BUILD{}.

So, Moose noob here, but are there examples elsewhere in the stack of
anybody doing this sort of thing with roles?  It seems they're all strictly
composition of methods and attributes with no state.

Thanks.


On Mon, Dec 22, 2014 at 1:24 PM, Rob Emery <notifications@github.com> wrote:

> @mnp <https://github.com/mnp> currently the Roles are used within the
> Goodie repo for any situation in which we want to share or encapsulate
> functionality; so it's not exactly inappropriate here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/duckduckgo/duckduckgo/pull/108#issuecomment-67871277>.
>



-- 
Mitchell Perilstein <mitchell.perilstein@gmail.com>
(484) 876-1444

**Comment by mnp** [comment]
ps - @rob pls see above.

On Tue, Jan 13, 2015 at 4:57 PM, Mitchell Perilstein <
mitchell.perilstein@gmail.com> wrote:

> Rob, just returning to this issue after a context switch.
>
> I'm not sure role is appropriate here because (1) this package has
> internal state -- inside Locale, setting its process globals :-(  -- which
> should be shared among all consumers, therefore (2) I need a way to
> initialize all this state, and (3) I'd like it done once among multiple
> callers.
>
> I didn't want to bring MooseX::Singleton into your stack, but that would
> have been nicer solution for (3) than a secret ghetto global.  Because of
> (1, 2), I want an initialization hook, and roles don't call BUILD{}.
>
> So, Moose noob here, but are there examples elsewhere in the stack of
> anybody doing this sort of thing with roles?  It seems they're all strictly
> composition of methods and attributes with no state.
>
> Thanks.
>
>
> On Mon, Dec 22, 2014 at 1:24 PM, Rob Emery <notifications@github.com>
> wrote:
>
>> @mnp <https://github.com/mnp> currently the Roles are used within the
>> Goodie repo for any situation in which we want to share or encapsulate
>> functionality; so it's not exactly inappropriate here.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/duckduckgo/duckduckgo/pull/108#issuecomment-67871277>
>> .
>>
>
>
>
> --
> Mitchell Perilstein <mitchell.perilstein@gmail.com>
> (484) 876-1444
>
>


-- 
Mitchell Perilstein <mitchell.perilstein@gmail.com>
(484) 876-1444

**Comment by moollaza** [comment]
@mnp did you mean to ping @mintsoft?

**Comment by mintsoft** [comment]
@mnp can't anything which needs to be done on initialisation just be done outside of any of the methods? Like so: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/GoodieRole/Dates.pm#L270

Or do you need to call code prior to the Roles being loaded?

**Comment by mintsoft** [comment]
Thanks @moollaza

**Comment by mnp** [comment]
Rob, I think it might be that simple.  I've already seen the Dates role
too, and hadn't noticed that.
I'll give it a try, thanks.

On Mon, Jan 19, 2015 at 7:42 AM, Rob Emery <notifications@github.com> wrote:

> @mnp <https://github.com/mnp> can't anything which needs to be done on
> initialisation just be done outside of any of the methods? Like so:
> https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/GoodieRole/Dates.pm#L270
>
> Or do you need to call code prior to the Roles being loaded?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/duckduckgo/duckduckgo/pull/108#issuecomment-70487038>.
>



-- 
Mitchell Perilstein <mitchell.perilstein@gmail.com>
(484) 876-1444

**Comment by zachthompson** [comment]
How would this be as [helper](https://github.com/duckduckgo/duckduckgo/blob/master/lib/DDG/Meta/Helper.pm) functions?  Just a thought.

**Comment by moollaza** [comment]
@zachthompson I think we need it to be in DDG because internally we'd still run into issues if both Spice and Goodies load a helper that declares aliases. It seems that if we want to use this lib we'd need to load it once and declare all the aliases in one place as well. DDG seems like the best place for that.

I know we're working to create a Perl function that will detect a location in a string and give us a country object back (or some form of that) so that alleviate the need for `Locale::Country`.

Alternatively, we may be able to ditch the lib if we re-create a much simpler version of it using its data file? https://metacpan.org/source/SBECK/Locale-Codes-3.34/internal/curr.yaml

**Comment by zachthompson** [comment]
It would just do the aliases/renames in a similar way to the current proposal, making sure it only happens once.  But frankly accessor functions/methods aren't really necessary.  As long as the aliases are added once somewhere, the IAs can still use Locale::Country::country2code/code2country.  These "pass through" methods don't prevent someone from trying to add an alias.  Only QC of the IA can prevent that.

**Comment by zachthompson** [comment]
[zach/test-locale](https://github.com/duckduckgo/duckduckgo/compare/zach/test-locale) is one way to do it.  It seems to me that this is more metadata than a role.

**Comment by zachthompson** [comment]
Fixed in https://github.com/duckduckgo/duckduckgo/pull/125

**Pull request closed without merging**
