### PR TITLE
DDG::Meta::CountryCodes - Centralize aliasing/renaming

### PR DESCRIPTION
**Pull request by zachthompson**
This is an alternative approach to https://github.com/duckduckgo/duckduckgo/pull/108 to centralize the renaming and aliasing of country codes to prevent warnings.  It tries to be minimal, allowing IAs to still use Locale::Country functions.

Are we ok with these renames?  I don't know the history behind them but I'm guessing it's so they are readable when displayed.

This needs to go with PRs [#1103](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1103) and [#1755](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1755) if we decide to move forward with it.

/cc @nilnilnil

### CODE REVIEW

**Comment by moollaza** [comment]
@zachthompson this LGTM. Tested and deployed locally. I think we'll need to add `Locale::Country` to the dist.ini though and we can also remove it from the IA repos?

**Comment by moollaza** [comment]
Would like @nilnilnil to signoff.

**Comment by zachthompson** [comment]
How about we just move to AutoPrereqs. ;) The IAs still use Locale::Country normally.  We will just have to disallow adding aliases or renaming in an IA.  Those will need to be added to DDG::Meta::CountryCodes if necessary.

**Comment by zachthompson** [comment]
Travis is failing because AutoPrereqs didn't catch Data::Printer https://github.com/duckduckgo/duckduckgo/blob/zach/test-locale/lib/DDG/Meta.pm#L50.   @moollaza do you know anything about why we did this?

**Comment by moollaza** [comment]
@zachthompson sorry, I just saw this comment!

I don't know why import `Data::Printer` into the IA packages like that. I imagine the thought was to prevent IA's from having to `use DDP` whenever devs wanted to print something? It's not documented, and I don't suppose it would be missed by anyone if we removed it.

**Comment by nilnilnil** [comment]
:+1:

**Pull request merged**
