### PR TITLE
Add timezone for Australia

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
@zachthompson We were missing a TZ for Australia!

/cc @mintsoft @MrChrisW

### CODE REVIEW

**Comment by zachthompson** [comment]
Malaysia as well, or am I missing something?

**Comment by GuiltyDolphin** [comment]
@zachthompson No, you're right!

**Comment by MrChrisW** [comment]
@zachthompson @GuiltyDolphin LGTM :+1:

**Comment by GuiltyDolphin** [comment]
Thanks @MrChrisW!

@zachthompson Can we get this published? I forgot it needs to be published before it takes affect and now I have failing builds! :cry:

**Comment by zachthompson** [comment]
For future reference, you can always override the installed version by adding the path to your git repo in your startup file, e.g.
```
export PERL5LIB="$HOME/duckduckgo/lib:$PERL5LIB"
```
I do this with many of the repos we release since master should be the same.

**Comment by GuiltyDolphin** [comment]
@zachthompson Oh, locally it's fine - I always work off the repo. I meant the Travis build was failing.

**Pull request merged**
