### PR TITLE
Removed case to set root by checking directory t

### PR DESCRIPTION
**Pull request by killerfish**
Fixes duckduckgo/p5-app-duckpan#229
Will need to check if this doesn’t break anything

### CODE REVIEW

**Comment by moollaza** [comment]
@killerfish I'm not sure this is the correct fix. I'd rather we fix that check for a `/t` dir, because the comment explains the need for that check. We should rather make sure that `$parent` isn't outside our repo. 

Surprisingly though, all the tests pass -- which potentially means we're just not testing this code correctly. I'd like to be 100% sure we're not breaking anything by removing this code.

**Comment by killerfish** [comment]
I think that case in the comment might be outdated, as the design would have changed over the course of 3 years, perhaps. It tells us that `lib` could be in `t`, which AFAIK doesn’t happen in any instant answer type, (`t` always contains the tests).

**Comment by moollaza** [comment]
@killerfish you're correct that it doesn't exist in our IA repos, but it does in others like DuckPAN and Duckduckgo:

- https://github.com/duckduckgo/p5-app-duckpan/tree/master/t/lib/DDG
- https://github.com/duckduckgo/duckduckgo/tree/master/t/lib/DDGTest

We should make sure these tests still pass and code works as expected

**Comment by killerfish** [comment]
Hmm, I still have to dive deeper into duckduckgo repo, but i believe ShareDir is only applicable on instant answers, also duckduckgo repo doesn’t seem to have a share directory, so if we then assume duckpan left, the tests pass for me. Unless im missing something. :thought_balloon:

**Comment by zachthompson** [comment]
@moollaza Do you have any other thoughts or concerns about this?  Be nice to get rid of it.  I started looking at the original report of this in https://github.com/duckduckgo/p5-app-duckpan/issues/11 yesterday before realizing it had been reported again and a PR created.  I think @killerfish is right.  This is applied functionality limited to the IAs.  All that could break would be the tests and prove seems fine.

**Comment by moollaza** [comment]
Whoops, forgot to reply to this, sorry @killerfish! 

@zachthompson I'm happy if you are with this.

**Pull request merged**
