### PR TITLE
Headers support

### PR DESCRIPTION
**Pull request by jbarrett**
This replaces the `accept_header` support (which is only used by 1 live Spice) with a generalised `headers` keyword.

Cc: @zachthompson @nilnilnil 

---

The affected Spice, has been fixed here: https://github.com/duckduckgo/zeroclickinfo-spice/pull/3056

### CODE REVIEW

**Comment by jbarrett** [comment]
The idea being you can:

```perl
spice headers => {
    Accept => 'application/vnd.citationstyles.csl+json',
    Connection => 'keep-alive'
}
```

...and so on.

Open question: Do values need wrapping in quotes?

**Comment by nilnilnil** [comment]
👍 -- will leave to @zachthompson for final

**Comment by jbarrett** [comment]
Calling this WIP - I think we need quoting (for the headers hash) and a reasonable pattern for adding basic auth.

**Comment by jbarrett** [comment]
Added quoting. Not adding sugar for basic auth - making basic auth strings from login credentials is a one liner, so we can do it easily.

The latest changes completely remove the header include update from #210 - this is included globally elsewhere. It also means that header changes we make using this functionality won't be wiped out by this include.

**Comment by jagtalon** [comment]
Ping!

**Comment by moollaza** [comment]
@jbarrett looks like there's a merge conflict (we merged in the `post_body` related code), but otherwise this looks good.

We only have 1 Spice using "accept_header", so updating the repo accordingly is trivial.

**Comment by moollaza** [comment]
@jbarrett I made a PR to fix the conflicts:

https://github.com/duckduckgo/duckduckgo/pull/228

**Comment by moollaza** [comment]
I have tested this with DuckPAN, using the SkySkanner PR, and my own CocoaPods Spice PR.

Support for headers has also been added to DuckPAN here: https://github.com/duckduckgo/p5-app-duckpan/pull/382

**Comment by jdorweiler** [comment]
Tested and looks good.

**Pull request merged**
