### PR TITLE
Use Test::Deep for goodie tests

### PR DESCRIPTION
**Pull request by zachthompson**
Testing a `structured_answer` with `Test::More::is_deeply` is not trivial and usually results in the data tests being essentially skipped, particular for IAs with variable results.

`Test::Deep::cmp_deeply` gives us more options in these cases.  Works with existing tests except for some that weren't using the [same pragmas in their tests](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2093).

@nilnilnil and @kablamo might be interested in this as well.

### CODE REVIEW

**Comment by moollaza** [comment]
To expand on Zach's comment, the benefit of moving to `Test::Deep` is that `Test::More` can only compare a hash against a 1-1 clone. 

If the hash we're testing contains any random or length data, the expected result hash we provide needs to be identical which is very difficult and cumbersome.

With `Test::Deep` we can use a regex or specifcy the expected type (e.g. `array` of `int`s) for any hash value making it much easier to test our Goodie Structured Answers.

Right now we're using a blanket `-Any-` which simply passes the test if we expect the Goodie to return _something_ on that query.

> example: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/10aef38a6105bb1c7f7bb28a45ad47d977d2a45a/t/Chess960.t#L18

**Comment by mintsoft** [comment]
This'll be awesome!

**Comment by GuiltyDolphin** [comment]
@zachthompson How's this going?

/cc @moollaza

**Comment by moollaza** [comment]
@GuiltyDolphin it looks like once we update the tests so that they don't expect `is_cached` to be a bignum anymore these changes will work.

**Comment by zachthompson** [comment]
@moollaza we still want to give this a shot?

**Comment by GuiltyDolphin** [comment]
@zachthompson @moollaza Yes please! :dolphin:

**Comment by GuiltyDolphin** [comment]
Ping @moollaza This LGTM! Are there any issues with getting this merged?

**Comment by zachthompson** [comment]
@GuiltyDolphin You want to review this?

**Comment by GuiltyDolphin** [comment]
@zachthompson Checked it out and it is sweet! We might want to indicate somewhere that people should import `Test::Deep` if they want the full testing power! :dolphin:

**Comment by GuiltyDolphin** [comment]
@zachthompson Hmm, maybe updating the template to import `Test::Deep` (rather than, or in addition to, `Test::More`) would do the trick?

**Pull request merged**
